### ISSUE TITLE
Accept any parameter transformation function for the XML tags

### ISSUE THREAD

**Issue by robyoder** [agilebits/t-i18n#4]
Instead of tying the ReactNode interpolation to the React paradigm, allow any function to be passed as the transformation function for the given node array. For example:

```
T.$(
	"Hi, {name}. Please <link>click <strong>here</strong></link> to read our style guide.",
	{
		link: (...children) => $.a({ href: "#" }, ...children, linkImage),
		name: this.state.userName,
		strong: partial($.strong, {}),
	},
)
```

In this case, the returned value would simply be an array of the React or string nodes. This would supersede my previous idea to use React.Fragment. (#2) Instead, `T.$` would accept XML and always return an array and `T` would not accept XML and would always return a string (same as now, just no React assumption). 

The calling code could wrap `T` to provide the Fragment feature or simply spread the result into the React code instead of putting it in as an array.

**Comment by robyoder** [comment]
There are two big benefits of this approach:

**1. API clarity** 

Right now, the API calls for an array (tuple) of React factory and React props to pass to the factory. But this is not super clear when just reading the code and doesn't type-check easily.

```
T.$(
	"<link>Click here</link> to read our style guide.",
	{ link: [$.a, { href: "#" }] },
)
```

And it's hard to include more pieces inside the same factory. You'd have to do something like this:

```
T.$(
	"<link>Click here</link> to read our style guide.",
	{ link: [(props, txt) => $.a(props, txt, myCoolImage), { href: "#" }] },
)
```

That's pretty ugly.

**2. Flexibility**

With this change you could create your nodes however you like, using JSX or even something besides React:

```
T.$(
	"<link>Click here</link> to read our style guide.",
	{ link: (txt) => <a href="#">txt <img src="myCoolImage.jpg" /></a> },
)
```

**Comment by mitchchn** [comment]
This is a really great idea. So `T.$` would read more like "T-dot-apply" than "T-dot-React". I was already unhappy with the tuple syntax and the unidiomatic React code, and I'm eager to remove React type dependencies from the repository. Would you be up for taking this on?
